"""empty message

Revision ID: 597237923a49
Revises: 8664a38630eb
Create Date: 2026-08-19 12:04:51.026598-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '597237923a49'
down_revision: Union[str, Sequence[str], None] = '8664a38630eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
